### ISSUE TITLE
Suggestion:add practical use cases of social network analytics in real-world 

### ISSUE THREAD

**Issue by junjielizero** [briatte/awesome-network-analysis#70]
How about add some materials not just research but also real-world examples

**Comment by peejs** [comment]
I agree with this suggestion but I suggest we be mindful not to end up with a list of commercial products (akin to classified ads).

**Comment by briatte** [comment]
@junjielizero Could you please provide examples of what you mean by real-world examples, please?

**Comment by peejs** [comment]
@junjielizero would something like this (https://www.aaai.org/ocs/index.php/WS/AAAIW17/paper/download/15101/14643) qualify as a real-world example? or would it still be "just research"? :)

**Comment by junjielizero** [comment]
@briatte https://www.dataminingapps.com/2017/01/5-practical-use-cases-of-social-network-analytics-going-beyond-facebook-and-twitter/ like this

**Comment by briatte** [comment]
@junjielizero Thank you for providing an example. I am, however, unconvinced by it: the most interesting part of the example is… the bibliography, which provides some actual analytical techniques (note that the article itself uses 'analytics' instead of analysis).

I'll stick with the current state of the collection right now -- that is, awesome resources to learn network analysis, rather than awesome applications.

**Comment by HamplusTech** [comment]
> @junjielizero would something like this (https://www.aaai.org/ocs/index.php/WS/AAAIW17/paper/download/15101/14643) qualify as a real-world example? or would it still be "just research"? :)

i tried opening the above link but it gives error (DB Error: Table 'sessions' is marked as crashed and should be repaired). please if you have the content of the link, kindly send to my email - hampojohnpaul@gmail.com.
Thanks.
